app/controllers/application_controller.rb
app/controllers/errors_controller.rb
app/views/errors/error_403.html.erb
config/routes.rb
spec/controllers/bulk_add_batches_controller_spec.rb
spec/controllers/errors_controller_spec.rb
spec/controllers/mappings_controller_spec.rb

- Users *shouldn't* see this, so don't include any extra information.

Make the "invalid authenticity token" 403 error pretty like the others

---

app/models/whitelisted_host.rb
spec/models/whitelisted_host_spec.rb

- Upon accidentally adding a host with trailing whitespace this morning, thanks to a failed copy/paste, I realised that the whitelist let it through without stripping the whitespace or erroring. Make it strip the whitespace from the hostname, so that people and Bouncer don't get confused or match on the wrong thing.

Strip trailing whitespace from hosts added to the whitelist

---

app/models/whitelisted_host.rb
spec/models/whitelisted_host_spec.rb

- Like we do for *.gov.uk and *.mod.uk, *.nhs.uk should not need
whitelisting. We were getting many requests for *.nhs.uk domains to
be whitelisted, from PHE's transition, and it's easier to deal with
them globally than have them ask us to add yet another to the
whitelist when they find one.

Add *.nhs.uk as an automatically allowed ending for a hostname

---

app/validators/host_in_whitelist_validator.rb
app/views/admin/whitelisted_hosts/index.html.erb
features/whitelist.feature
lib/transition/path_or_url.rb
spec/models/mapping_spec.rb

- This is needed otherwise the validations of whitelisted hosts disallow mappings to be added for, for example, `somethingnotexplicitlywhitelistedyet.nhs.uk` A good spot by Jenny pre-deploy of https://github.com/alphagov/transition/pull/485. :sunny:

Allow adding mappings to *.nhs.uk hosts

---

db/migrate/20150320164433_remove_individual_nhsuk_domains_from_whitelist.rb
db/schema.rb

- Anything ending in .nhs.uk is now automatically whitelisted. See
https://github.com/alphagov/transition/pull/485 and
https://github.com/alphagov/transition/pull/486. This is the tidying
up migration to remove the hosts we'd manually added to the
whitelist before we made the global change.

Remove the specific *.nhs.uk hosts from the whitelist list

---

app/models/bulk_add_batch.rb
app/models/import_batch.rb
app/validators/host_in_whitelist_validator.rb
app/views/errors/error_503.html.erb
app/views/shared/_error_messages.html.erb
config/application.rb
config/locales/en.yml
features/mapping_edit.feature
features/step_definitions/mappings_assertion_steps.rb
spec/models/bulk_add_batch_spec.rb
spec/models/import_batch_spec.rb
spec/models/mapping_spec.rb

- The team behind the transition-dev@ mailing list was dissolved a few
months ago in the GOV.UK restructure. The email address is still
active and they still receive sporadic whitelist requests for
domains. These requests are now fielded via second-line support, and
so should go to Zendesk. Given that people using the Transition Tool
are inside government departments or agencies, they should know what
Zendesk is and how to send queries via it, without us having to link
explicitly to it.

Update the whitelist and support request email address to cite Zendesk

---

lib/tasks/import/revert.rake
lib/transition/import/revert.rb
spec/lib/transition/import/revert_spec.rb

We occasionally configure sites and then later decide that they should not be
transitioned via the Transition tool. In these cases it's good to delete the
imported site so that the data reflects our decisions. An example of such a
site is the content planner application on alphagov.co.uk: this app is [no
longer in Production](https://github.com/alphagov/transition-config/pull/1128) before the move to publishing.service.gov.uk so we don't
need to redirect the old domain, but it has already been imported.
This rake task makes it easier to delete these sites and all associated data
which may have been created by the site import: hosts and links to extra
organisations. The site should be removed from the transition-config repo
before running the task, otherwise the site will be re-imported …

Add a rake task to revert import of some sites

---

app/helpers/versions_helper.rb
app/models/import_batch.rb
app/models/import_batch_entry.rb
app/models/mappings_batch.rb
app/presenters/batch_preview_presenter.rb
app/views/import_batches/preview.html.erb
app/views/mappings/_form.html.erb
db/migrate/20150715141152_add_archive_url_to_mappings_batch_entries.rb
db/schema.rb
features/mapping_edit.feature
features/mapping_import.feature
features/step_definitions/mappings_assertion_steps.rb
features/step_definitions/mappings_import_assertion_steps.rb
features/step_definitions/mappings_import_interaction_steps.rb
features/step_definitions/mappings_interaction_steps.rb
lib/transition/import/csv/import_batch_row.rb
spec/helpers/versions_helper_spec.rb
spec/lib/transition/import/csv/import_batch_row_spec.rb
spec/models/bulk_add_batch_spec.rb
spec/models/import_batch_spec.rb
spec/support/shared_examples/mappings_batch.rb

A Site has many Mappings and user can bulk import mappings from a CSV.
One of the available types of Mappings is an Archive Mapping. An Archive Mapping has an Old URL and an Archive URL.
A Site has a National Archives timestamp and its Archive Mappings can either construct their Archive URL using that timestamp or they can specify their own custom Archive URL.
Until now we've ignored any custom Archive URLs that were defined in an imported CSV (and instead let the imported Archive Mappings default to constructing their Archive URLs from their Site's timestamp as described above).
These updates change that behaviour, so that we now respect custom Archive URLs in CSVs and persist them along with their Mapping.

Allow defining custom archive URLs in a bulk import

---

lib/transition/import/whitehall/mappings.rb

We're no longer using the alphagov.co.uk domain for our applications, so
should get the correct domain from the environment via Plek. Since the
migration to the *.publishing.service.gov.uk domains this import [has been
erroring with `OpenURI::HTTPError: 401 Unauthorized`](https://errbit.publishing.service.gov.uk/apps/530f56010da115868600173d/problems/56022747657863061e671402) - I suspect the basic
auth credentials aren't being passed along when following the redirect.
This changes the behaviour to use Whitehall in the current environment rather
than always using Production, but there is no mention in git history of any
reason for doing that. It's more helpful to test against the current
environment so that any errors due to changes in Whitehall can be detected
before getting to …

Use correct domain for Whitehall mappings import

---

app/validators/host_in_whitelist_validator.rb
app/views/errors/error_503.html.erb
config/locales/en.yml
spec/models/bulk_add_batch_spec.rb
spec/models/import_batch_spec.rb
spec/models/mapping_spec.rb

We've moved domain names in production. The old ones are redirected but we should update them anyway.

Update alphagov domain name in production

---

lib/tasks/import/revert_entirely_unsafe.rake
lib/transition/import/revert_entirely_unsafe.rb
spec/lib/transition/import/revert_entirely_unsafe_spec.rb

- ONS domains and data need to be removed from transition as they would like to add a different service
- The rake task takes a site abbreviation as a parameter and removes all associated data from the following tables: 
- mappings
- versions
- daily_hit_totals
- host_paths
- sites
- organisational_relationships
- organisations_sites
- The hits files in the hits directory are not removed.
https://trello.com/c/WVYEPfxG/252-delete-all-data-for-www-ons-gov-uk-in-transition

Add rake task to remove site and all data

---

README.md

- If you've not got a Trusty VM (with PostgreSQL 9.3 by default),
you'll need to destroy and reprovision to get the latest one, but
it's the default now, so don't recommend `govuk_dev_dist=trusty`.
(Found this looking through the branches list. It's still relevant, so I'm raising a very delayed PR!)

The dev VM is Trusty by default now, so no need for `govuk_dev_dist`

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
config/initializers/govuk_admin_template.rb
features/organisations.feature

* Add automatic email stripping on GA events
* Use admin template config
* Use standard sign out block in navbar
* Set app title in config
Part of https://trello.com/c/E2aEKfMM/352-automatically-strip-email-addresses-from-ga-events-in-admin-tools

Bump admin gem to 4.2.0

---

db/migrate/20140613165318_add_postgres_crypto.rb
db/migrate/20141120164444_drop_pgcrypto.rb

- Setting up Transition on a new laptop, I replicated data and then had
to run `rake db:migrate`. It failed on the "enable pgcrypto" migration
because it requires database superuser access to enable extensions. We
don't need this extension anymore (it was removed in November 2014),
so comment out migrations that reference it so that `db:migrate` can
run cleanly. Commenting out rather than deleting because I don't know
how Rails behaves when you delete migrations, and so that we preserve
history of these changes.

Comment out some migrations so that first time setup runs cleanly

---

app/helpers/hits_helper.rb
spec/helpers/hits_helper_spec.rb

Between 28/04/2016 and 03/05/2016 the hits graphs suddenly gained a black line for every day, instead of only for the transition date:
I can't see any relevant changes in the Google Charts release notes [1] - the last documented release was in February, long before we started seeing these problems.
The documentation for chart annotations [2] says that the default value for the annotation role is `''`, which suggests that our existing code should still work, but the examples on that page use `null` for datapoints without annotations. Switching our default value in the helper to `nil` appears to fix the problem, and the annotation for the transition date is shown correctly:
[1]: https://developers.google.com/chart/interactive/docs/release_notes#official-releases
[2]: …

Fix black lines on hits graphs

---

lib/transition/import/hits/ignore.rb
spec/fixtures/hits/furniture_paths.tsv
spec/lib/transition/import/hits_spec.rb

We already ignore hits rows which contain various patterns which indicate that we don't need to map them, such as `.js`, but we do want to import hits rows with `.jsp` - this is an extension used by Java Spring apps.
This commit updates the pattern to match either `.js$` or `.js<any non-word character>` so that any `.js` paths with query strings are still matched. This enables us to import `.jsp` hits.
I don't intend to reimport all the hits files after this change has been deployed. There's one site in particular which I know is affected by this (`directgov_local`) so we will reimport those hits files from pre-transition-stats.
I found this problem while working on mappings for that site - we know that we want to map URLs like http://local.direct.gov.uk/LDGRedirect/index.jsp?LGSL=57 but …

Import hits with .jsp extension

---

app/views/organisations/show.html.erb
features/organisation.feature
features/step_definitions/organisation_interaction_steps.rb

Several organisations have lots of sites now, which makes it harder to find the one you're looking for in the table. Making the table filterable, as we do for the organisations index, helps with this.
GDS has by far the most sites (214; FCO has 163, BIS 66 and UKTI 58) and the majority of organisations have only one site, so this is very much scratching our own itch. Should we only add the filter header row if there are more than 5 sites, or are we happy for it to be there for everyone?

Make the sites table filterable

---

app/models/mapping.rb
app/views/shared/_tag_list_field.html.erb
features/mapping_tag.feature
features/step_definitions/mappings_assertion_steps.rb
spec/models/mapping_spec.rb

For https://trello.com/c/ZYSIdD8R/466-tags-in-edit-mapping-form-are-mangled-transition-3
Previously the text_field for a tag_list_field would merge multiple tags into one string (ie with multiple tags would be filled with words only separated by a space, e.g. "fee fi of"). On saving the mapping, this would create a new tag. The problem seems to have been that when using the FormHelper text_field method, calling the `tag_list` method did not return a comma separated string. So we explicitly set the value to be the string-ified array.
In order to make testing easier, we replace `acts_as_taggable` with `acts_as_ordered_taggable` which ensures that the tags remain ordered. Due to some interplay between the 'paper-trail' and the 'acts-as-taggable-on' gems, this requires a change to the ignore …

Fix tag list field to fill with comma separated tags

---

features/step_definitions/mappings_assertion_steps.rb

The test was failing in CI because when passing a comma-separated string
and turning it into an array, the leading white spaces would not be removed
and therefore elements would not be matched correctly.
```
expected collection contained:  [" fi", " fo", "fee"]
actual collection contained:    [" fee", " fi", "fo"]
```
This commit removes leading and trailing whitespace for the elements.

Remove whitespace from tag_list in cucumber step

---

config/initializers/gds-sso.rb

This change will allow transition to use auth tokens defined in hiera when it's deployed.
This should eliminate the need to replace the file each time per environment.

Govuk Transition signon config

---

config/initializers/gds-sso.rb

This isn't prefixed with `SIGNON`.

Fix name of Signon environment variable

---

spec/lib/transition/import/whitehall_orgs_spec.rb
spec/support/webmock.rb

In #526 we bumped gds-api-adapters to get a fix for list responses from
the api.  We only spotted the failure when trying to run the whitehall
orgs import in production because our existing specs have a different
codepath that uses a fixture instead of the API.  We add a spec that does
use the API (albeit stubbed via the gds_api/test_helpers) which should
protect us against similar failures when the API changes in the future.

Add a spec to cover WhitehallOrgs#load_orgs_from_api

---

app/views/organisations/show.html.erb
features/organisation.feature

When filtering sites from the org show page, pressing enter to go to the top
result didn't work because I missed this class out of #520. Add it to fix it.

Fix filter navigation on pressing enter for sites

---

app/controllers/mappings_controller.rb
spec/controllers/mappings_controller_spec.rb

- This caused me problems when copying and pasting from a spreadsheet
into the "go to site or mapping box" - I pasted something with
trailing whitespace and it didn't go anywhere.
- So, strip both leading and trailing whitespace from the
`params[:url]` field before processing it further.

Strip whitespace from the URL in MappingsController#find_global

---

db/migrate/20161111172455_change_column_types_on_mappings_batch_entries.rb
db/schema.rb
spec/models/import_batch_spec.rb

In particular because `archive_url` was too small for National Archives URLs which are usually long. Batch entries are the precursor to mappings so their column types should match where possible, so that users can create mappings via batches with the same constraints as when doing them individually.
Also use a long `archive_url` in a test which fails without this migration.
See Errbit for [examples of data which trigger this problem](https://errbit.publishing.service.gov.uk/apps/530f56010da115868600173d/problems/5825f6646578633fd99a0b00) - the test URL comes from this data.
There's some context for the large schema diff in the first commit message.
https://trello.com/c/MGtcYgQV/549-fix-limit-on-archive-url-length-when-importing-batches-in-transition

Change column types on mappings_batch_entries to match mappings

---

app/models/host.rb
spec/models/host_spec.rb

Nothing in production is using this IP address anymore:
```
irb(main):002:0> Host.where(ip_address: '46.137.92.159').count
=> 0
```

Remove `AMAZON_LEGACY_IP`

---

features/support/poltergeist.rb

We've got intermittent-ish test failures around the charts js in Transition
again, which get in the way of us making even small unrelated changes to the
app. This time it's variations on this in the hits_summary feature.
We're disabling raising of javascript errors in Poltergeist so that we can get
builds running again.  We've got a [card for investigating the issue further][1]
in our backlog.
Trello story: https://trello.com/c/nvjibWTy/633-transition-test-failures
[1]: https://trello.com/c/kaQn2aYB/528-transition-test-failures

Suppress javascript errors in Poltergeist

---

app/models/host.rb
spec/models/host_spec.rb

Fastly have set up a service map for Bouncer and have allocated us new
IP address for that map.
We should be moving things away from the other 2 methods of redirection
and should be using just this one map.

Add new Fastly IP addresses

---

lib/tasks/clear_expired_sessions.rake
lib/tasks/clear_old_mappings_batches.rake

The method `destroy_all` no longer receives arguments, it needs a where
clause to be invoked uppon.
Trello:
https://trello.com/c/UunoKJk9/186-overnight-transition-rake-tasks-failing-in-production

Fix scheduled rake tasks - destroy_all

---

app/models/host.rb

In the very old days we used a Dyn HTTP redirect service for direct.gov.uk and businesslink.gov.uk. We've now changed those redirects to use Bouncer.
There are only 2 domains left in Transition which use these IP addresses. They are not actively redirecting so they need to be removed before this is merged and deployed.

Remove Dyn DNS redirect IP addresses

---

config/initializers/govuk_basic_auth.rb
lib/tasks/import/whitehall.rake

These environment variables are currently available on prod, they were added in https://github.com/alphagov/govuk-puppet/pull/6325 by @boffbowsh.
https://trello.com/c/bxvXAF4S

Use environment variables for WH basic auth

---

config/database.yml

This is to remove the need for [database.yml][] to be copied in at the
time of deployment.
This switches this script to be based around the use of DATABASE_URL env
vars which already exist in [govuk-puppet][]
[database.yml]:
https://github.com/alphagov/alphagov-deployment/blob/5cca0de76b1c1e4a122933aac199f8f0587ded70/transition/to_upload/database.yml
[govuk-puppet]:
https://github.com/alphagov/govuk-puppet/blob/f127d3c209c38ee95c3b222c7fa102ad988ed915/modules/govuk/manifests/apps/transition.pp#L98-L104

Refactor database.yml for ENV["DATABASE_URL"]

---

app/controllers/application_controller.rb

This method has been deprecated in gds-sso v13.3.0 [1] and should be
replaced with authenticate_user!
[1] https://github.com/alphagov/gds-sso/blob/master/CHANGELOG.md#1330
---
Previously https://github.com/alphagov/transition/pull/560

Remove deprecated require_signin_permission!

---

Jenkinsfile

- This was extracted into https://github.com/alphagov/govuk-jenkinslib and the
docs updated to specify this as the new way of loading the library.

Update Jenkinsfile to use the external govuk library

---

lib/transition/import/whitehall_orgs.rb

- The Jenkins jobs loading the config for transition are currently
talking to whitehall-admin.internal/api/organisations, while the api
is exposed via www.gov.uk/api/organisations as well
- During AWS migration, internal access to whitelladmin is temporary
unavailable so we need this change for the config updates to work
- After AWS migration I still do not find the idea of keeping it too
bad, because it is a test of the external facing API if anything...
solo: @schmie

Hard-code the external api/organisations for config

---

lib/transition/import/whitehall/mappings.rb
spec/lib/transition/import/whitehall/mappings_spec.rb

These files are 30MB each, so downloading one twice a day and never deleting them is eating up disk space in production.
Normally these would be removed as old release directories are deleted, but this app is not deployed very often.

Fix disk space issues by deleting import files after use

---

spec/factories/daily_hit_totals.rb
spec/factories/hits.rb
spec/factories/hosts.rb
spec/factories/mappings.rb
spec/factories/mappings_batch.rb
spec/factories/organisations.rb
spec/factories/sites.rb
spec/factories/users.rb

The way of doing it before will be removed in later versions of factory bot.

Use blocks to define factory fields

---

spec/controllers/hits_controller_spec.rb
spec/helpers/sites_helper_spec.rb

It's bad practice to freeze time without returning it afterwards as it can affect other tests as it was doing here.

Return frozen time to fix flaky tests elsewhere

---

lib/tasks/import/orgs_sites_hosts.rake

This means that it shows up in the list of rake tasks. This task is useful
if you want to import a single site config file repeatedly as you're working
on it.

Add a description for import:orgs_sites_hosts task

---

app/models/host.rb
spec/models/host_spec.rb

Transition needs to know the IP addresses and hostnames used by Bouncer in order to correctly report the transition status of sites and hosts.
@timblair asked us to use these IP addresses if we weren't able to use CNAME, ANAME or ALIAS records, rather than the anycast IPs.
Also tweak the tests for `redirected_by_gds?` to cover these cases better.

Add new Bouncer IP addresses

---

lib/transition/import/hits_mappings_relations.rb

We're seeing [a problem while running the import that the `site` is `nil`](https://deploy.blue.production.govuk.digital/job/transition_import_hits/31/console).
```
Adding missing mapping_id/canonical_path to host paths ... 
rake aborted!
NoMethodError: undefined method `site' for nil:NilClass
/data/vhost/transition/releases/20190715125102/lib/transition/import/hits_mappings_relations.rb:65:in `block in connect_mappings_to_host_paths!'
```
Instead of failing the entire import, we should warn that this is the case.

 Allow site to be nil while importing

---

.rubocop.yml

- As of govuk-lint 3.11.2, govuk-lint doesn't include Performance
Rubocops because they were split out from the core Rubocop gem.
- This config here causes warnings in `govuk-lint-ruby` output because
we don't require 'rubocop-performance' to get these Performance cops:
`Warning: unrecognized cop Performance/Casecmp found in .rubocop.yml`
- Given that the Performance cops were removed so many versions of
govuk-lint ago, I'm going to take a punt that we don't need them in
this app and so we can get rid of this line to get rid of three (!)
warnings.

Remove config for Performance/Casecmp Rubocop

---

app/views/admin/whitelisted_hosts/index.html.erb
spec/controllers/admin/whitelisted_hosts_controller_spec.rb

Navigating to the "Redirection Whitelist" in Transition Admin is error in the admin application with "We're sorry something went wrong". This is reflected in Sentry by a "ActionView::Template::Error: undefined method `originator'"
The WhitelistedHost model does not contain an `originator` field.
Instead this is exposed by `paper_trail` (a gem that provides version
history on a model) which the model has referenced.
Update the view so we refer to `originator` through `paper_trail` rather
than directly on the model. This should fix the error we are seeing.

Reach into paper trail to display originator

---

features/site.feature

2014 doesn't appear in the select list once the date rolls around to 2020.

Fix date specific test

---

config/cucumber.yml
features/support/allow_rescue.rb
features/support/set_javascript_flag.rb
spec/lib/transition/import/whitehall_orgs_spec.rb

- See commits for more detail on the specific deprecations.
- The reason for this is that ahead of upgrading to Rails 6, I ran the
tests locally to make sure my Docker setup worked. I noticed some of
these which will only get lost in all of the Rails upgrade related
deprecations, so fix them first then Dependabot can rebase.

Fix gem deprecation warnings

---

lib/transition/import/hits.rb

- This has been failing on Production for a few days (since the Rails
6 upgrade last week):
```
rake aborted!
NameError: uninitialized constant Transition::Import::Hits::Services
/data/vhost/transition/releases/20200313120259/lib/transition/import/hits.rb:80:in `from_s3!'
```
- It was missing `require "services"`. I have no idea why all these
explicit `require`s have suddenly needed to happen, but we fixed a few
of them in 4a81e0bed4d808a23116a52b47fe6d5ae6590526, but obviously not enough.
- It's probably worth doing a deeper investigation into what changed in
Rails 6 to make them not implicit any more, but this fixes the
immediate problem that hits data for transitioned sites is not getting
in.

Fix missing `require` in hits import script

---

.rubocop.yml
Rakefile
app/controllers/mappings_controller.rb
app/validators/is_path_validator.rb
lib/tasks/lint.rake
lib/transition/import/hits.rb

- This is a prerequisite for being able to move more of our apps to GitHub Actions. We want one single step `bundle exec rake` that runs everything. This ensures parity between local dev and what CI runs (something that we don't always have now).
- The state of `rubocop-govuk` has moved on since we first hand-crafted this `.rubocop.yml`. While we're here I thought we'd better make this as consistent as possible with upstream and stop overriding really old cops, or cops that were easily (ie auto-) fixable.
https://trello.com/c/5Gob6WUL/147-for-everyone-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks

Run RuboCop as part of `bundle exec rake`

---

.gitignore
Gemfile
Gemfile.lock
features/support/env.rb
spec/rails_helper.rb

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
We should always monitor the amount of code that is exercised when
we run our tests.

Use SimpleCov to monitor code coverage

---

app/controllers/hosts_controller.rb
spec/controllers/hosts_controller_spec.rb

This should help new hosts appear in that endpoint very soon after they are imported. We're seeing an issue where the [Bouncer import job](https://github.com/alphagov/govuk-cdn-config/blob/master/lib/deploy_bouncer.rb#L109) is running too soon after the [Transition import job](https://github.com/alphagov/transition/blob/master/lib/transition/import/sites.rb) and misses some of the newly importers hosts as the controller is likely to be cached by Nginx/Varnish.

Make hosts endpoint expire immediately

---

spec/controllers/hits_controller_spec.rb
spec/helpers/sites_helper_spec.rb

`around(:all)` is invalid syntax when placed on a context. `around(:example)`
works on contexts and has the desired effect.
Warning from rspec:
```
WARNING: `around(:context)` hooks are not supported and behave like `around(:example).
```

Swap `around(:all)` for `around(:example)`

---

README.md

Adds a link to the [transition config](https://github.com/alphagov/transition-config) repo to the readme of this repo.
During a recent 2nd line shift, it wasn't clear to me how to add URLs to the transition tool and I had to ask, where I was point to transition-config. This directs devs to the right place quicker.

Add a link to transition-config in the readme

---

config/initializers/session_store.rb

After upgrading activerecord-session_store we hit a problem with our logging (see rails/activerecord-session_store#176 for more details).
The logger provided to us by govuk_app_config doesn't have support for the silence method, so we can add it in place here. If we find that we're needing to this to lots of our applications, we should move it into govuk_app_config.
This should resolve https://sentry.io/organizations/govuk/issues/2303356396/?referrer=slack.

Include ActiveSupport::LoggerSilence

---

Jenkinsfile
config/database.yml

This changes the JenkinsFile to use postgres 13.
Postgres 13 is available at port `54313` on the CI server. By explicitly 
setting the `TEST_DATABASE_URL`, we're telling Rails to use that 
Postgres server.
Previously, Rails implicitly used the default Postgres port `5432` which 
is a Postgres 9.6 server.
Trello ticket: https://trello.com/c/zVdVJqFM

Use postgres 13 when running tests in CI

---

config/brakeman.ignore
lib/transition/distributed_lock.rb

As Redis.current ultimately calls Redis.new we can migrate this method now to pave the way for future upgrades.
From Redis changelog from [5.0][1]:
‘Removed Redis.current. You shouldn't assume there is a single global Redis connection, use a connection pool instead, and libaries using Redis should accept a Redis instance (or connection pool) as a config. E.g. MyLibrary.redis = Redis.new(…).’
[Redis.current][2] just calls Redis.new so should just be able to swap methods.
[trello](https://trello.com/c/oGFWhrCO/1551-migrate-away-from-deprecated-redis-method)

Use Redis.new rather than Redis.current

---

db/migrate/20221020085112_change_host_to_text.rb
db/schema.rb

Previously, this was limited to 255 characters, and was causing the daily import job to fail when trying to insert a hostname longer than this, leading to a loss of analytics.
After this is merged, we will want to re-run the import job.
[Trello](https://trello.com/c/AekXHbPg/317-fix-transition-daily-hits-import-job)

Change hostname to text

---

.github/pull_request_template.md

This warns about continuous deployment when creating a pull request.
[Trello card](https://trello.com/c/VgRHbI98)

Add PR template for Continuous Deployment

---

.dockerignore
Dockerfile
Gemfile
Gemfile.lock
config/application.rb
config/boot.rb
spec/support/jasmine-browser.json

- Fix Rails assets deployment to S3 by including the app name in the Rails assets path.
- Parameterise the Ruby version.
- Enable [bootsnap](https://github.com/Shopify/bootsnap#bootsnap-).
- Remove some hard-coded paths.
- Clean up `.dockerignore`.
- Make better use of `WORKDIR`.
- Remove the now-redundant `bundle exec` from the default command.
Tested: builds and comes up healthy on the integration Kubernetes cluster.

Dockerfile fixes and cleanup.

---

config/brakeman.ignore
lib/transition/distributed_lock.rb

Adds a second lock inside the current lock in the DistributedLock method.
This is a first step to cleaning up a little tech debt. We want to remove the environment from the lock name (not necessary because all environments have their own redis anyway, and undesirable because it requires a brakeman ignore).
However, these rake tasks are run by cron jobs and it's not necessarily possible to ensure that the job won't be running when the app is deployed, so if we just change the lock name there's a possibility two instances will try to run the task, one with the old lock, one with the new one. So here we require both locks. Once this is deployed and a day has passed we can deploy with the new lock only, safe in the knowledge that if we deploy during a rake run it'll already be locking the new …

Add double-lock, in preparation for simplifying lock name

---

config/brakeman.ignore
lib/transition/distributed_lock.rb

Removes the original lock, moving us to the simplified lock name added here: https://github.com/alphagov/transition/pull/1314
Can be merged once a safe period of time has passed (min 24 hours after original pull merged, so Thu May 11th would be reasonable)
https://trello.com/c/84yWQ0NJ/1662-ps-15-clean-up-brakeman-errors-following-on-from-rediscurrent-redisnew-updates

Remove original lock onces a safe time has passed

---

app/models/user.rb
features/step_definitions/authentication_steps.rb
spec/factories/users.rb

We are in the process of archiving Transition Config, which requires that we add various bits of functionality to Transition.
In order to test these safely, we have added a new `Site manager` permission to Signon.
This adds the permission to the user model, as well as some test helpers.
---

Add `Site manager` permission

---

app/controllers/sites_controller.rb
app/forms/site_form.rb
app/models/concerns/nilify_blanks.rb
app/models/host.rb
app/models/site.rb
app/views/organisations/show.html.erb
app/views/sites/new.html.erb
config/breadcrumbs.rb
config/locales/en.yml
config/routes.rb
features/site.feature
features/step_definitions/site_interaction_steps.rb
spec/controllers/sites_controller_spec.rb
spec/factories/site_forms.rb
spec/forms/site_form_spec.rb
spec/models/host_spec.rb
spec/models/site_spec.rb
spec/requests/site_creation_spec.rb
spec/support/shared_examples/authentication.rb

> [!NOTE]  
> This is not the finished article, this is for us to refine as we learn more about how it will be used.
https://trello.com/c/3NYAPZs4
We want to add a new site form. In order to do this we will need an easy way to
access these values.
We might want to consider refining these further into enums, as this would
allow us to remove some of the methods in the site model.
We want to add sites per organisation.
This add nested routes for site creation.
We are aiming to archive Transition Config which is currently used to create
sites in Transition.
This adds a form object for the creation of a site. 
It's worth noting that the process currently moves existing hosts and aka hosts
to the new site if they already exist (see
`lib/transition/import/site_yaml_file.rb`). We aren't yet sure …

Add new transition form

---

app/controllers/sites_controller.rb
app/forms/delete_site_form.rb
app/views/sites/confirm_destroy.html.erb
features/step_definitions/site_interaction_steps.rb
spec/forms/delete_site_form_spec.rb

https://trello.com/c/MP3g273Q
Now that we have introduced a layout for the Design System, we should ensure that we are using it when adding new pages.
The most appropriate way of showing the `The confirmation did not match` message while following the Design System seems to be to use form validation, so this also introduces a form object to back the delete form. This has the additional benefit of moving the deletion logic out of the controller.
|Before|After|
|-|-|
|![image](https://github.com/alphagov/transition/assets/47089130/fb27ad17-7c90-4423-a797-3c3d4d4f9a06)|![image](https://github.com/alphagov/transition/assets/47089130/d1658ea2-f388-4481-ac2e-22b3d008f0ce)|
---
This application is owned by the publishing platform team. Please let us know in #govuk-publishing-platform when you …

Move delete site confirmation page to the Design System

---

app/models/host.rb
spec/models/host_spec.rb

https://trello.com/c/Aaao9833
The current import process will move a host to a new site if a site with that
same host already exists (documented in
`spec/lib/transition/import/site_yaml_file_spec.rb:177`).
We think this will not happen frequently, so have decided to disallow adding or
updating a host where the hostname is not unique.
All hostnames in the database are currently unique, so this validation can run
on create and update without invalidating any current records.
Note that this executes 2 SQL queries, whereas we could perform this in 1 if
using custom validation, however I think using the built in validation in
clearer for this use case.
---
⚠️ This …

Validate that hostnames are unique

---

app/views/layouts/application.html.erb
app/views/layouts/error_page.html.erb
config/initializers/current_release_sha.rb

This has been broken since we moved to EKS and the SHA is no longer provided.
We can use the [SENTRY_RELEASE](https://github.com/alphagov/govuk-helm-charts/blob/077117e7f40c096a958f9e0b853a2bd76cf43f26/charts/generic-govuk-app/templates/deployment.yaml#L92C1-L92C1) environment variable which is defined for every app and takes its value from the container image's tag.
If for whatever reason the image tag is not defined it will display `null`, which should make it clearer (instead of displaying `development`) that this data is not being pulled in successfully.
Trello card: https://trello.com/c/uoKDUcbV/3182-fix-broken-version-footer-in-publishing-apps-2
⚠️ This …

Fix release version in footer

---

lib/tasks/import/revert.rake
spec/lib/tasks/import/revert_spec.rb
spec/rails_helper.rb

There may be times that a host needs to be removed. This is currently not possible (although will be when we make the edit site UI available to users).
Therefore adding a rake task to allow us to remove hosts when they are no longer needed.
The corresponding change will also need to be made in `transition-config` to stop the host being reimported again.

Add rake task to remove a host

---

app/models/mapping.rb
app/models/user.rb
features/mapping_history.feature
spec/models/mapping_spec.rb

[Trello](https://trello.com/c/cWDsJqHc/853-remove-unused-method-and-field-from-transition)

(853) Remove unused methods

---

lib/tasks/import/all.rake
lib/tasks/import/orgs_sites_hosts.rake
lib/transition/import/orgs_sites_hosts.rb
spec/lib/transition/import/orgs_sites_hosts_spec.rb
spec/lib/transition/import/revert_entirely_unsafe_spec.rb
spec/lib/transition/import/revert_spec.rb

**Note**:  should be coordinated with https://github.com/alphagov/govuk-helm-charts/pull/1296
Separate the responsibilities so we can invoke separate tasks for importing organisations and importing sites and hosts, respectively.
This allows us to keep as much of the existing tests as possible, to make the path towards removing the dependency on transition-config safer and clearer.
This separation will also allow us to modify the cron job to only invoke the importing of organisations from whitehall.
[Trello](https://trello.com/c/toGB61iI/809-remove-cron-job-that-imports-site-data-from-transition-config-to-transition-then-archive-the-transition-config-repo)
⚠️ …

Split off orgs_sites_hosts import task

---

db/migrate/20231017095753_convert_paper_trail_yaml_to_json.rb
db/schema.rb
lib/tasks/migrate_paper_trail.rake

https://trello.com/c/FTU5uYu4
> [!NOTE]  
> Once we have successfully run the Rake task in this PR, we can merge [part 2](https://github.com/alphagov/transition/pull/1433)
> [!NOTE]  
> I've tested this by running it in integration, this all looks fine:
> - Adding new PaperTrail versions are now JSON
> - Killing the migration task and restarting it picks up where it left off
> - Migrated objects are as expected
PaperTrail version 13 has a breaking change for users who use the YAML
serialiser for the `object` and `object_changes` columns
(https://github.com/paper-trail-gem/paper_trail/blob/master/doc/pt_13_yaml_safe_load.md).
PaperTrail strongly suggest that best solution is to convert these YAML
columns to JSON.
The first step is to add new JSON columns for `object` and `object_changes`, …

Update PaperTrail - part 1

---

app/forms/site_form.rb
spec/forms/site_form_spec.rb

The values of the extra organisations select component correspond to the record
IDs. Currently, when the form is loaded, the previous selection is not shown correctly.
---

Load the selected extra organisations into the site form correctly

---

app/controllers/organisations_controller.rb
spec/controllers/organisations_controller_spec.rb

https://trello.com/c/tSMIkxGp
We removed the abbr attribute for new sites in #1473.
This page raises an error when a new site without an abbr is present.
Sort by hostname instead. All sites have a default host with a hostname (confirmed in the console with `Site.all.map { |site| site.default_host.hostname }.all? { |hostname| hostname.present? }`)
---

Fix error when a site doesn't have an abbr

---

.github/workflows/deploy.yml
Dockerfile

This switches the build workflow to the multi-arch format so we can start getting ARM-compatible builds ready.

Switch to the multi-arch workflow for ARM builds

---

app/views/layouts/_google_tag_manager.html.erb
app/views/layouts/application.html.erb

Based on the work we did previously on publisher in alphagov/publisher#1963
Because we already have a content_for :head block in this application, there's a very slight departure from the approach taken in publisher / signon - the layouts/google_tag_manager partial renders the tag directly, instead of setting content_for.
Tested locally with:
GOOGLE_TAG_MANAGER_AUTH=some-auth
GOOGLE_TAG_MANAGER_ID=some-id
GOOGLE_TAG_MANAGER_PREVIEW=some-preview
Gives this snippet in <head>:
<script>
//<![CDATA[
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl+'&gtm_cookies_win=x&gtm_auth=some-auth&gtm_pre …

Add Google Tag Manager configuration to Transition

---

config/application.rb

When upgrading to Rails 7.0 in https://github.com/alphagov/transition/pull/1166/commits/68b50fce7f903887ebbf6ad85b714f81d821b8e6, we added some code to rotate SHA1 cookies to SHA256. A `TODO` comment was left to remove the code after the rotation had taken place, but this was never done.
Removing the code as it has served it's purpose of rotating the cookies.

Remove cookie rotation code from Rails 7.0 upgrade

---

Gemfile
Gemfile.lock
config/application.rb
spec/requests/null_byte_spec.rb

We have been seeing exceptions `string contains null byte (ArgumentError)` logged in Sentry for this application.
These are a result of an automated scan being run by Cyber Security which includes a null byte in the request (we believe it is in the session cookie).  No vulnerability is present, but the resulting error thrown by the application has resulted in a lot of noise in our Sentry alerts.
Adding a test to reproduce this problem so we are able to fix it.  Sanitising request URIs, headers and cookies to prevent the exception being raised again.
[Trello card](https://trello.com/c/B0hXNjfb)

Sanitize and cleanup invalid UTF-8 characters

---

lib/tasks/temp/change_beis_site_orgs.rake

Add temporary task for changing old beis site orgs

---

Gemfile
README.md

From a cursory look through the git history, I can't find any documentation about why these need to be in sync, but under the assumption this is still correct, this makes the comments more complete
See:
- https://github.com/alphagov/bouncer/commit/cae58279aabafd8225f71fa0e90f02a10711e650
- https://github.com/alphagov/bouncer/commit/c6791bdff0ce593df35cfda7d8571ea75dbaa2b6
- https://github.com/alphagov/bouncer/pull/143#discussion_r119315712
- https://github.com/alphagov/transition/commit/e9266720fe92e8b8d9c2771bf4fc30385bba8137#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR8
---
⚠️ This repo is Continuously Deployed: make sure you …

Update Bouncer sync comments in Gemfile

---

app/assets/javascripts/application.js

[Trello](https://trello.com/c/uB3b0Pt5/1344-fix-transition-radio-button-bug-to-allow-users-to-add-new-sites-when-selecting-a-global-type-of-redirect)
A form conditional in `app/views/sites/_site_form.html.erb` (which appears on the "New transition site" page) was not being revealed when the relevant radio option was selected. We weren't requiring the related JavaScript, so this does that
---
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are …

Fix non-revealing form conditional

---

app/assets/stylesheets/legacy/filters.scss
app/assets/stylesheets/legacy/tags.scss

[Trello](https://trello.com/c/RrKHuZkH/1361-fix-sass-deprecations-in-transition)
This fixes the following deprecation warning:
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
```
See: https://sass-lang.com/documentation/breaking-changes/slash-div
---

Fix Sass slash as division deprecations

---

yarn.lock

We had a medium security vulnerability because jasmine-browser-runner depends on express 4.20.0 which depends on serve-static 0.16.0 which depends on send 0.18.0, which is currently vulnerable due to https://github.com/advisories/GHSA-m6fv-jmcg-4jfg.
The changes to yarn.lock were generated by running `yarn up -R express` to ensure it's using the patched version (0.19.0) of the send dependency.
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you …

Update express dependency to fix vulnerability

---

app/views/layouts/application.html.erb

Trello: https://trello.com/c/vB0leYNw/1393-fix-breadcrumbs-wcag-fails-in-transition
After: 

Remove breadcrumbs to appease WCAG

---

config/environments/production.rb

The previous regex permitted `app-name.dodgygov.uk`. Updating to disallow this and only permit `*.gov.uk`.
[Trello card](https://trello.com/c/frqFN7D8)

Update hosts for application

---

package.json
yarn.lock

This updates the dependency `path-to-regexp` to a newer version.
Resolves https://github.com/alphagov/transition/security/dependabot/68.
[Trello card](https://trello.com/c/qvmUj6qK)

Update `express` npm package to version 4.21.2

---

app/sidekiq/mappings_batch_job.rb

Sidekiq::Worker was deprecated a while back and
[we switched over](https://github.com/alphagov/transition/commit/1817374062f3cccda0e7f6f6777ea301447c988f)
to using Sidekiq::Job here and moved this file from app/workers.
I assume there's a reason that we kept these bits when we made those
changes. Some sort of compatibility issue?
Anyway, this setup is now preventing RSpec from running at all on my
machine. (I think it's the difference between the naming of the
MappingsBatchJob constant and its file.) So I'm hoping that it's not
needed anymore.

Remove all traces of old Sidekiq "worker" naming

---

Gemfile.lock
app/views/sites/_site_form.html.erb
app/views/sites/confirm_destroy.html.erb

Update all uses of the textarea component to change the `id` option to `textarea_id`.
Tests in this PR are likely to fail until the changes to the textarea component are included in this PR with a new gem release.
Changes in https://github.com/alphagov/govuk_publishing_components/pull/4574 mean that this option needs to be updated.
Shouldn't be any.
Trello card: https://trello.com/c/GQ1p2oSC/438-not-doing-add-component-wrapper-helper-to-form-textarea-component

Update calls to textarea with the id option
